<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MachiVerse.AdminView</RootNamespace>
    <AssemblyName>MachiVerse.AdminView</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all" />
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="all" />
    <PackageReference Include="Tomlyn" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="../../docs/protocols/schema/common.proto" ProtoRoot="../../docs/protocols/schema" GrpcServices="None" Link="Protocol/Schema/common.proto" />
    <Protobuf Include="../../docs/protocols/schema/auth.proto" ProtoRoot="../../docs/protocols/schema" GrpcServices="None" Link="Protocol/Schema/auth.proto" />
    <Protobuf Include="../../docs/protocols/schema/payloads.proto" ProtoRoot="../../docs/protocols/schema" GrpcServices="None" Link="Protocol/Schema/payloads.proto" />
  </ItemGroup>
</Project>
